# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Course(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, start=None, end=None, amount=None, id=-1):  # noqa: E501
        """Course - a model defined in OpenAPI

        :param name: The name of this Course.  # noqa: E501
        :type name: str
        :param start: The start of this Course.  # noqa: E501
        :type start: date
        :param end: The end of this Course.  # noqa: E501
        :type end: date
        :param amount: The amount of this Course.  # noqa: E501
        :type amount: int
        :param id: The id of this Course.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'name': str,
            'start': date,
            'end': date,
            'amount': int,
            'id': int
        }

        self.attribute_map = {
            'name': 'name',
            'start': 'start',
            'end': 'end',
            'amount': 'amount',
            'id': 'id'
        }

        self._name = name
        self._start = start
        self._end = end
        self._amount = amount
        self._id = id

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Course of this Course.  # noqa: E501
        :rtype: Course
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Course.

        Name of the course  # noqa: E501

        :return: The name of this Course.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Course.

        Name of the course  # noqa: E501

        :param name: The name of this Course.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) < 2:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `2`")  # noqa: E501

        self._name = name

    @property
    def start(self):
        """Gets the start of this Course.

        Start date of the course  # noqa: E501

        :return: The start of this Course.
        :rtype: date
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Course.

        Start date of the course  # noqa: E501

        :param start: The start of this Course.
        :type start: date
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def end(self):
        """Gets the end of this Course.

        Graduation date of the course  # noqa: E501

        :return: The end of this Course.
        :rtype: date
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Course.

        Graduation date of the course  # noqa: E501

        :param end: The end of this Course.
        :type end: date
        """
        if end is None:
            raise ValueError("Invalid value for `end`, must not be `None`")  # noqa: E501

        self._end = end

    @property
    def amount(self):
        """Gets the amount of this Course.

        Number of lectures that make up the training course  # noqa: E501

        :return: The amount of this Course.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Course.

        Number of lectures that make up the training course  # noqa: E501

        :param amount: The amount of this Course.
        :type amount: int
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501
        if amount is not None and amount > 255:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value less than or equal to `255`")  # noqa: E501
        if amount is not None and amount < 1:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `1`")  # noqa: E501

        self._amount = amount

    @property
    def id(self):
        """Gets the id of this Course.

        Course ID in the database, value -1 if there is no corresponding record in the DB  # noqa: E501

        :return: The id of this Course.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Course.

        Course ID in the database, value -1 if there is no corresponding record in the DB  # noqa: E501

        :param id: The id of this Course.
        :type id: int
        """

        self._id = id
