# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class SearchData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, start=None, end=None):  # noqa: E501
        """SearchData - a model defined in OpenAPI

        :param name: The name of this SearchData.  # noqa: E501
        :type name: str
        :param start: The start of this SearchData.  # noqa: E501
        :type start: date
        :param end: The end of this SearchData.  # noqa: E501
        :type end: date
        """
        self.openapi_types = {
            'name': str,
            'start': date,
            'end': date
        }

        self.attribute_map = {
            'name': 'name',
            'start': 'start',
            'end': 'end'
        }

        self._name = name
        self._start = start
        self._end = end

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SearchData of this SearchData.  # noqa: E501
        :rtype: SearchData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this SearchData.

        Name of the course  # noqa: E501

        :return: The name of this SearchData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SearchData.

        Name of the course  # noqa: E501

        :param name: The name of this SearchData.
        :type name: str
        """
        if name is not None and len(name) < 2:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `2`")  # noqa: E501

        self._name = name

    @property
    def start(self):
        """Gets the start of this SearchData.

        Start date of the course  # noqa: E501

        :return: The start of this SearchData.
        :rtype: date
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this SearchData.

        Start date of the course  # noqa: E501

        :param start: The start of this SearchData.
        :type start: date
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this SearchData.

        Graduation date of the course  # noqa: E501

        :return: The end of this SearchData.
        :rtype: date
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this SearchData.

        Graduation date of the course  # noqa: E501

        :param end: The end of this SearchData.
        :type end: date
        """

        self._end = end
